KiderProjectWeb/Controllers/AboutController.cs
using Business.Abstract;
using KiderProjectWeb.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace KiderProjectWeb.Controllers
{
    public class AboutController : Controller
    {
        private readonly IAboutService _aboutService;
        private readonly ITeacherService _teacherService;


        public AboutController(IAboutService aboutService,ITeacherService teacherService)
        {
            _aboutService = aboutService;
            _teacherService = teacherService;
        }

        public IActionResult Index()
        {
            var aboutData = _aboutService.GetAll().Data;
            var teacherData = _teacherService.GetTeacherWithPositions().Data;
            AboutViewModel viewModel = new()
            {
                Abouts = aboutData,
                Teachers = teacherData,
            };
            return View(viewModel);
        }
    }
}

KiderProjectWeb/Controllers/AppointmentController.cs
using Business.Abstract;
using Core.Results.Concrete;
using Entities.Concrete.Dtos;
using Microsoft.AspNetCore.Mvc;

namespace KiderProjectWeb.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly IAppointmentService _appointmentService;
        public AppointmentController(IAppointmentService appointmentService)
        {
            _appointmentService = appointmentService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(AppointmentCreateDto appointment)
        {

            var result = _appointmentService.Add(appointment);
            if (!result.IsSuccess)
            {
                var errorResult = result as ErrorResult;
                if (errorResult != null)
                {
                    ModelState.Clear();
                    foreach (var error in errorResult.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }
                }
                return View(appointment);
            }

            TempData["SuccessMessage"] = "Məlumat uğurla göndərildi!";
            return RedirectToAction("Index");


        }
    }
}

KiderProjectWeb/Controllers/ContactController.cs
using Business.Abstract;
using Core.Results.Concrete;
using Entities.Concrete.Dtos;
using Microsoft.AspNetCore.Mvc;

namespace KiderProjectWeb.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactService _contactService;

        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(ContactCreateDto dto)
        {
            var result = _contactService.Add(dto);
            if (!result.IsSuccess)
            {
                var errorResult = result as ErrorResult;
                if (errorResult != null)
                {
                    ModelState.Clear();
                    foreach (var error in errorResult.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }
                }
                return View(dto);
            }
            TempData["SuccessMessage"] = "Məlumat uğurla göndərildi!";
            return RedirectToAction("Index");
        }
    }
}

KiderProjectWeb/Controllers/TeacherController.cs
using Business.Abstract;
using KiderProjectWeb.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace KiderProjectWeb.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherService _teacherService;

        public TeacherController(ITeacherService teacherService)
        {
            _teacherService = teacherService;
        }
        public IActionResult Index()
        {
            var teacherData = _teacherService.GetTeacherWithPositions().Data;
            TeacherViewModel viewModel = new()
            {
                Teachers = teacherData,
            };
            return View(viewModel);
        }
    }
}

KiderProjectWeb/Areas/Dashboard/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Custom fonts for this template-->
    <link href="~/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/admin/css/sb-admin-2.min.css" rel="stylesheet">

    <link href="~/admin/vendor/datatables/datatables.bootstrap4.min.css" rel="stylesheet" />
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-action="Index" asp-controller="Home">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Kider</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Facility">
                    <i class="fa-solid fa-school"></i>
                    <span>Bağça imkanları</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Appointment">
                    <i class="fa-regular fa-calendar-check"></i>
                    <span>Uşaq qeydiyyatı</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Contact">
                    <i class="fa-regular fa-address-book"></i>
                    <span>Əlaqə</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="About">
                    <i class="fa-solid fa-circle-info"></i>
                    <span>Haqqımızda</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="SchoolClass">
                    <i class="fa-solid fa-person-chalkboard"></i>
                    <span>Siniflər</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Position">
                    <i class="fa-solid fa-user-tie"></i>
                    <span>Peşələr</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Slide">
                    <i class="fa-regular fa-window-restore"></i>
                    <span>Slide</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="TeacherCandidate">
                    <i class="fa-regular fa-address-card"></i>
                    <span>Müəllim qeydiyyatı</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Testimonial">
                    <i class="fa-regular fa-comments"></i>
                    <span>Rəy</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Teacher">
                    <i class="fa-solid fa-chalkboard-user"></i>
                    <span>Müəllim</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="SchoolClassTeacher">
                    <i class="fa-solid fa-chalkboard-user"></i>
                    <span>Sinif ve muellim</span>
                </a>
            </li>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                   aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="~/admin/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-action="LogOut" asp-controller="Account">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>İstifadəçi Paneli</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/admin/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/admin/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/admin/js/demo/chart-area-demo.js"></script>
    <script src="~/admin/js/demo/chart-pie-demo.js"></script>

    <script src="~/admin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/admin/js/demo/datatables-demo.js"></script>

    <script src="~/admin/vendor/sweetalert2/sweetalert2.all.js"></script>
    <script src="~/admin/vendor/sweetalert2/sweetalert2.all.min.js"></script>
    <script src="~/admin/vendor/sweetalert2/sweetalert2.js"></script>
    <script src="~/admin/vendor/sweetalert2/sweetalert2.min.js"></script>


    <script>
        document.querySelectorAll('.partial-text').forEach(item => {
            item.addEventListener('mouseover', function () {
                this.querySelector('.visible-text').style.display = 'none';
                this.querySelector('.hidden-text').style.display = 'inline';
            });

            item.addEventListener('mouseout', function () {
                this.querySelector('.visible-text').style.display = 'inline';
                this.querySelector('.hidden-text').style.display = 'none';
            });
        });
    </script>


    @RenderSection("Scripts", false)
</body>

</html>